import type { Word } from "./types";

// Seed dataset — 10 canonical words across TOPIK I / II levels.
// Every entry carries the full content anatomy mandated by the spec §4-2:
//   • 4 example sentences (Korean + English gloss + highlight token)
//   • 3 collocations (natural phrases used by native speakers)
//   • Hanja / etymology breakdown for Sino-Korean words
//   • Morphology (prefix/root/suffix) where relevant
//   • Synonyms + antonyms
//   • AI Mnemonic (English syllable hook)
// Bulk content (2,000+ words) will be produced by the Claude + Stability AI
// pipeline (see /internal/generate-content-continuous in the ops repo).
export const SEED_WORDS: Word[] = [
  {
    id: "w_pogihada",
    word: "포기하다",
    romanization: "pogihada",
    ipa: "/po̞.ɡi.ɦa̠.da/",
    definitionEn: "to give up; to abandon",
    partOfSpeech: "VERB",
    level: 2,
    exam: "TOPIK_I",
    conceptImageUrl: "/images/concept/pogihada.svg",
    mnemonic: {
      englishHint: "PO-GI-HA-DA → POst it and GO, HA! Done Already.",
      syllables: ["포", "기", "하", "다"],
    },
    etymology: {
      origin: "抛棄",
      language: "Sino-Korean",
      rootWords: [
        { char: "抛", meaning: "throw", sound: "포" },
        { char: "棄", meaning: "abandon", sound: "기" },
      ],
      evolution: "抛棄 (Sino-Korean compound) + 하다 (verbalizing suffix)",
      originEn: "抛 (throw away) + 棄 (discard) → 'to throw away and discard'.",
    },
    morphology: { root: "포기", suffix: "하다", note: "Noun + 하다 verb construction" },
    examples: [
      { sentence: "저는 꿈을 포기하지 않아요.", translation: "I don't give up on my dreams.", highlight: "포기" },
      { sentence: "시험을 포기하면 안 돼요.", translation: "You must not give up on the exam.", highlight: "포기" },
      { sentence: "그는 결국 포기했다.", translation: "He eventually gave up.", highlight: "포기" },
      { sentence: "쉽게 포기하지 마세요.", translation: "Don't give up easily.", highlight: "포기" },
    ],
    collocations: [
      { phrase: "꿈을 포기하다", translation: "to give up on a dream" },
      { phrase: "희망을 포기하다", translation: "to give up hope" },
      { phrase: "계획을 포기하다", translation: "to abandon a plan" },
    ],
    synonyms: ["단념하다", "체념하다"],
    antonyms: ["계속하다", "도전하다"],
    tags: ["emotion", "willpower"],
  },
  {
    id: "w_gamsahada",
    word: "감사하다",
    romanization: "gamsahada",
    ipa: "/ka̠m.sʰa̠.ɦa̠.da/",
    definitionEn: "to be thankful; to thank",
    partOfSpeech: "VERB",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "GAM-SA → 'GUM SAck' you thank a friend for sharing.",
      syllables: ["감", "사", "하", "다"],
    },
    etymology: {
      origin: "感謝",
      language: "Sino-Korean",
      rootWords: [
        { char: "感", meaning: "feel", sound: "감" },
        { char: "謝", meaning: "thank", sound: "사" },
      ],
      evolution: "感謝 (Sino-Korean) + 하다 (verbalizer)",
      originEn: "感 (to feel) + 謝 (to thank) → 'to feel gratitude'.",
    },
    morphology: { root: "감사", suffix: "하다" },
    examples: [
      { sentence: "정말 감사합니다.", translation: "Thank you very much.", highlight: "감사" },
      { sentence: "도와주셔서 감사해요.", translation: "Thank you for your help.", highlight: "감사" },
      { sentence: "선물 감사합니다.", translation: "Thanks for the gift.", highlight: "감사" },
      { sentence: "늘 감사하는 마음으로 살아요.", translation: "I live with a grateful heart.", highlight: "감사" },
    ],
    collocations: [
      { phrase: "감사 인사", translation: "a word of thanks" },
      { phrase: "감사의 마음", translation: "feeling of gratitude" },
      { phrase: "감사 드립니다", translation: "I give my thanks (formal)" },
    ],
    synonyms: ["고맙다"],
    antonyms: ["원망하다"],
    tags: ["daily", "etiquette"],
  },
  {
    id: "w_gyeongheom",
    word: "경험",
    romanization: "gyeongheom",
    ipa: "/kjʌ̹ŋ.ɦʌ̹m/",
    definitionEn: "experience",
    partOfSpeech: "NOUN",
    level: 3,
    exam: "TOPIK_II_MID",
    mnemonic: {
      englishHint: "GYEONG-HEOM → 'GONE HOME' with stories to tell — that's experience.",
      syllables: ["경", "험"],
    },
    etymology: {
      origin: "經驗",
      language: "Sino-Korean",
      rootWords: [
        { char: "經", meaning: "pass through", sound: "경" },
        { char: "驗", meaning: "test", sound: "험" },
      ],
      evolution: "經驗 — used in classical Chinese from Han dynasty philosophy texts.",
      originEn: "經 (pass through) + 驗 (test) → 'what one has gone through and tested'.",
    },
    examples: [
      { sentence: "저는 한국에서 일한 경험이 있어요.", translation: "I have experience working in Korea.", highlight: "경험" },
      { sentence: "좋은 경험이 되었어요.", translation: "It was a good experience.", highlight: "경험" },
      { sentence: "그는 경험이 많은 의사이다.", translation: "He is an experienced doctor.", highlight: "경험" },
      { sentence: "새로운 경험을 해 보고 싶어요.", translation: "I want to try new experiences.", highlight: "경험" },
    ],
    collocations: [
      { phrase: "경험을 쌓다", translation: "to accumulate experience" },
      { phrase: "경험이 풍부하다", translation: "to be rich in experience" },
      { phrase: "경험을 살리다", translation: "to make use of one's experience" },
    ],
    synonyms: ["체험", "경력"],
    antonyms: ["무경험"],
    tags: ["abstract", "work"],
  },
  {
    id: "w_areumdapda",
    word: "아름답다",
    romanization: "areumdapda",
    ipa: "/a̠.ɾɯm.da̠p̚.t͈a̠/",
    definitionEn: "to be beautiful",
    partOfSpeech: "ADJ",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "A-REUM-DAP-DA → 'A ROOM DAPpled with light' — beautiful.",
      syllables: ["아", "름", "답", "다"],
    },
    etymology: {
      origin: "아름 + -답다",
      language: "Native",
      rootWords: [
        "아름 (middle Korean: a full armful)",
        "-답다 (suffix: is like / is worthy of)",
      ],
      evolution: "'A full armful worth' → that which is worthy of one's embrace = beautiful.",
      originEn: "Native Korean. Something 'as full and worthy as one's embrace'.",
    },
    morphology: { root: "아름", suffix: "-답다", note: "Native root + descriptive adjective suffix" },
    examples: [
      { sentence: "한국의 가을은 정말 아름다워요.", translation: "Korean autumn is truly beautiful.", highlight: "아름" },
      { sentence: "그녀의 목소리가 아름답다.", translation: "Her voice is beautiful.", highlight: "아름" },
      { sentence: "아름다운 풍경이네요.", translation: "What a beautiful view.", highlight: "아름" },
      { sentence: "아름다운 기억만 남았어요.", translation: "Only beautiful memories remain.", highlight: "아름" },
    ],
    collocations: [
      { phrase: "아름다운 풍경", translation: "a beautiful landscape" },
      { phrase: "아름다운 마음", translation: "a beautiful heart" },
      { phrase: "아름다운 추억", translation: "beautiful memories" },
    ],
    synonyms: ["예쁘다", "곱다"],
    antonyms: ["못생기다", "추하다"],
    tags: ["nature", "aesthetic"],
  },
  {
    id: "w_annyeong",
    word: "안녕하세요",
    romanization: "annyeonghaseyo",
    ipa: "/a̠n.njʌ̹ŋ.ɦa̠.sʰe̞.jo̞/",
    definitionEn: "hello (polite greeting)",
    partOfSpeech: "INTERJ",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "AN-NYEONG → 'ARE YOU YOUNG?' — traditional polite greeting.",
      syllables: ["안", "녕", "하", "세", "요"],
    },
    etymology: {
      origin: "安寧",
      language: "Sino-Korean",
      rootWords: [
        { char: "安", meaning: "peace", sound: "안" },
        { char: "寧", meaning: "tranquil", sound: "녕" },
      ],
      evolution: "安寧하다 (to be at peace) → 안녕하세요 (polite interrogative greeting).",
      originEn: "Literally 'are you at peace?' — a wish for the listener's wellbeing.",
    },
    examples: [
      { sentence: "안녕하세요, 만나서 반갑습니다.", translation: "Hello, nice to meet you.", highlight: "안녕" },
      { sentence: "선생님, 안녕하세요.", translation: "Hello, teacher.", highlight: "안녕" },
      { sentence: "여러분, 안녕하세요!", translation: "Hello, everyone!", highlight: "안녕" },
      { sentence: "안녕하세요? 저는 민수입니다.", translation: "Hello, I'm Minsu.", highlight: "안녕" },
    ],
    collocations: [
      { phrase: "안녕히 가세요", translation: "goodbye (to someone leaving)" },
      { phrase: "안녕히 계세요", translation: "goodbye (to someone staying)" },
      { phrase: "안녕히 주무세요", translation: "good night (formal)" },
    ],
    synonyms: ["안녕", "하이"],
    tags: ["daily", "etiquette"],
  },
  {
    id: "w_gongbuhada",
    word: "공부하다",
    romanization: "gongbuhada",
    ipa: "/ko̞ŋ.bu.ɦa̠.da̠/",
    definitionEn: "to study",
    partOfSpeech: "VERB",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "GONG-BU → ring the GONG and open the BOOk — time to study.",
      syllables: ["공", "부", "하", "다"],
    },
    etymology: {
      origin: "工夫",
      language: "Sino-Korean",
      rootWords: [
        { char: "工", meaning: "work", sound: "공" },
        { char: "夫", meaning: "effort", sound: "부" },
      ],
      evolution: "工夫 originally meant 'the effort of artisans'; evolved to 'study' in Korean.",
      originEn: "工 (work) + 夫 (effort) → 'to put in effort to learn'.",
    },
    morphology: { root: "공부", suffix: "하다" },
    examples: [
      { sentence: "저는 한국어를 공부해요.", translation: "I study Korean.", highlight: "공부" },
      { sentence: "도서관에서 공부하고 있어요.", translation: "I'm studying at the library.", highlight: "공부" },
      { sentence: "매일 두 시간씩 공부한다.", translation: "I study for two hours every day.", highlight: "공부" },
      { sentence: "열심히 공부하세요.", translation: "Please study hard.", highlight: "공부" },
    ],
    collocations: [
      { phrase: "열심히 공부하다", translation: "to study hard" },
      { phrase: "한국어를 공부하다", translation: "to study Korean" },
      { phrase: "시험 공부", translation: "exam preparation" },
    ],
    synonyms: ["배우다", "학습하다"],
    antonyms: ["놀다"],
    tags: ["school", "daily"],
  },
  {
    id: "w_sarang",
    word: "사랑하다",
    romanization: "saranghada",
    ipa: "/sʰa̠.ɾa̠ŋ.ɦa̠.da̠/",
    definitionEn: "to love",
    partOfSpeech: "VERB",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "SA-RANG → 'SARANG' rhymes with 'SUNG' — sung from the heart.",
      syllables: ["사", "랑", "하", "다"],
    },
    etymology: {
      origin: "사랑",
      language: "Native",
      rootWords: [
        "사랑 (native Korean noun: love)",
        "-하다 (verbalizer)",
      ],
      evolution: "One of the oldest recorded native Korean words — appears in 15th-century Hangul texts.",
      originEn: "A pure native Korean word with no Hanja root.",
    },
    morphology: { root: "사랑", suffix: "하다" },
    examples: [
      { sentence: "저는 당신을 사랑해요.", translation: "I love you.", highlight: "사랑" },
      { sentence: "가족을 사랑합니다.", translation: "I love my family.", highlight: "사랑" },
      { sentence: "음악을 사랑하는 사람.", translation: "A person who loves music.", highlight: "사랑" },
      { sentence: "자기 자신을 사랑하세요.", translation: "Love yourself.", highlight: "사랑" },
    ],
    collocations: [
      { phrase: "사랑에 빠지다", translation: "to fall in love" },
      { phrase: "사랑을 고백하다", translation: "to confess one's love" },
      { phrase: "사랑을 받다", translation: "to be loved" },
    ],
    synonyms: ["아끼다", "좋아하다"],
    antonyms: ["미워하다", "증오하다"],
    tags: ["emotion", "kdrama"],
  },
  {
    id: "w_chwijik",
    word: "취직",
    romanization: "chwijik",
    ipa: "/t͡ɕʰɥi.d͡ʑik̚/",
    definitionEn: "getting a job; employment",
    partOfSpeech: "NOUN",
    level: 4,
    exam: "TOPIK_II_MID",
    mnemonic: {
      englishHint: "CHWI-JIK → 'CHOOSE the JOB' — you got hired.",
      syllables: ["취", "직"],
    },
    etymology: {
      origin: "就職",
      language: "Sino-Korean",
      rootWords: [
        { char: "就", meaning: "take up", sound: "취" },
        { char: "職", meaning: "post", sound: "직" },
      ],
      evolution: "就職 — a Sino-Korean term also shared with modern Japanese (shūshoku).",
      originEn: "就 (take up) + 職 (post / position) → 'to take up a position'.",
    },
    examples: [
      { sentence: "대학 졸업 후 취직했어요.", translation: "I got a job after graduating.", highlight: "취직" },
      { sentence: "요즘 취직이 어려워요.", translation: "It's hard to get a job these days.", highlight: "취직" },
      { sentence: "한국 회사에 취직하고 싶어요.", translation: "I want to get a job at a Korean company.", highlight: "취직" },
      { sentence: "취직 준비를 하고 있어요.", translation: "I'm preparing for the job market.", highlight: "취직" },
    ],
    collocations: [
      { phrase: "취직 활동", translation: "job-hunting" },
      { phrase: "취직 시험", translation: "employment exam" },
      { phrase: "취직이 되다", translation: "to get hired" },
    ],
    synonyms: ["취업", "입사"],
    antonyms: ["퇴직", "실업"],
    tags: ["work", "EPS"],
  },
  {
    id: "w_yaksok",
    word: "약속",
    romanization: "yaksok",
    ipa: "/ja̠k̚.s͈o̞k̚/",
    definitionEn: "a promise; an appointment",
    partOfSpeech: "NOUN",
    level: 2,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "YAK-SOK → 'YAK, sock it to me' — a promise is a handshake locked in.",
      syllables: ["약", "속"],
    },
    etymology: {
      origin: "約束",
      language: "Sino-Korean",
      rootWords: [
        { char: "約", meaning: "bind", sound: "약" },
        { char: "束", meaning: "tie", sound: "속" },
      ],
      evolution: "約束 — literally 'to bind and tie', metaphor for an unbreakable commitment.",
      originEn: "約 (bind) + 束 (tie) → 'to bind and tie' = a sworn commitment.",
    },
    examples: [
      { sentence: "내일 친구와 약속이 있어요.", translation: "I have plans with a friend tomorrow.", highlight: "약속" },
      { sentence: "약속을 꼭 지키세요.", translation: "Please keep your promise.", highlight: "약속" },
      { sentence: "그 약속은 못 지켰어요.", translation: "I couldn't keep that promise.", highlight: "약속" },
      { sentence: "우리는 다시 만나기로 약속했다.", translation: "We promised to meet again.", highlight: "약속" },
    ],
    collocations: [
      { phrase: "약속을 지키다", translation: "to keep a promise" },
      { phrase: "약속을 잡다", translation: "to make an appointment" },
      { phrase: "약속을 어기다", translation: "to break a promise" },
    ],
    synonyms: ["언약", "서약"],
    antonyms: ["거짓말", "배신"],
    tags: ["social", "daily"],
  },
  {
    id: "w_computer",
    word: "컴퓨터",
    romanization: "keompyuteo",
    ipa: "/kʰʌ̹m.pʰju.tʰʌ̹/",
    definitionEn: "computer",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "KEOM-PYU-TEO → just say 'computer' with a Korean accent.",
      syllables: ["컴", "퓨", "터"],
    },
    etymology: {
      origin: "computer (English)",
      language: "Loanword",
      rootWords: ["영어: computer"],
      evolution: "Direct transliteration; alternatives like 전자계산기 (電子計算機) never caught on.",
      originEn: "Pure loanword from English, written in Hangul phonetically.",
    },
    examples: [
      { sentence: "저는 컴퓨터를 좋아해요.", translation: "I like computers.", highlight: "컴퓨터" },
      { sentence: "컴퓨터가 고장 났어요.", translation: "The computer is broken.", highlight: "컴퓨터" },
      { sentence: "매일 컴퓨터로 일해요.", translation: "I work on a computer every day.", highlight: "컴퓨터" },
      { sentence: "새 컴퓨터를 샀어요.", translation: "I bought a new computer.", highlight: "컴퓨터" },
    ],
    collocations: [
      { phrase: "컴퓨터 게임", translation: "computer game" },
      { phrase: "컴퓨터를 켜다", translation: "to turn on the computer" },
      { phrase: "컴퓨터를 끄다", translation: "to turn off the computer" },
    ],
    synonyms: ["PC", "전산기"],
    tags: ["technology", "loanword"],
  },

  // ─── TOPIK I · Level 1 pack (2026-04 addition) ───────────────────────────
  // Ten high-frequency L1 words covering food, places, time, family and
  // basic motion / state verbs. Bulk catalog (2,000+ words) still lands via
  // the Claude + Stability AI pipeline — this pack is just enough to make
  // every dashboard category render useful content today.
  {
    id: "w_bap",
    word: "밥",
    romanization: "bap",
    ipa: "/pa̠p̚/",
    definitionEn: "cooked rice; a meal",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "BAP → 'BOP' your spoon on the bowl of rice before you eat.",
      syllables: ["밥"],
    },
    etymology: {
      origin: "밥",
      language: "Native",
      rootWords: ["Native Korean root — attested in 15th-century Hangul texts."],
      originEn:
        "Native Korean; metonymically means 'a meal' because rice is the default staple.",
    },
    examples: [
      { sentence: "밥 먹었어요?", translation: "Have you eaten? (a common greeting).", highlight: "밥" },
      { sentence: "저는 매일 밥을 먹어요.", translation: "I eat rice every day.", highlight: "밥" },
    ],
    collocations: [
      { phrase: "밥을 먹다", translation: "to eat a meal" },
      { phrase: "밥을 짓다", translation: "to cook rice" },
    ],
    synonyms: ["식사", "진지"],
    tags: ["food", "daily"],
  },
  {
    id: "w_mul",
    word: "물",
    romanization: "mul",
    ipa: "/mul/",
    definitionEn: "water",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "MUL → 'MOOOL'-ticup glass of water. Drink it all.",
      syllables: ["물"],
    },
    etymology: {
      origin: "물",
      language: "Native",
      rootWords: ["Native Korean; 'mur' in older Korean."],
      originEn: "One of the basic Native Korean nouns — no Hanja root.",
    },
    examples: [
      { sentence: "물 한 잔 주세요.", translation: "Please give me a glass of water.", highlight: "물" },
      { sentence: "물이 차가워요.", translation: "The water is cold.", highlight: "물" },
    ],
    collocations: [
      { phrase: "물을 마시다", translation: "to drink water" },
      { phrase: "찬물 / 따뜻한 물", translation: "cold water / warm water" },
    ],
    tags: ["food", "daily"],
  },
  {
    id: "w_byeongwon",
    word: "병원",
    romanization: "byeongwon",
    ipa: "/pjʌ̹ŋ.wʌ̹n/",
    definitionEn: "hospital; clinic",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "BYEONG-WON → 'BEING WON over' back to health at the hospital.",
      syllables: ["병", "원"],
    },
    etymology: {
      origin: "病院",
      language: "Sino-Korean",
      rootWords: [
        { char: "病", meaning: "illness", sound: "병" },
        { char: "院", meaning: "institution", sound: "원" },
      ],
      originEn: "病 (illness) + 院 (institution) → 'an institution for illness'.",
    },
    examples: [
      { sentence: "병원에 가야 해요.", translation: "I have to go to the hospital.", highlight: "병원" },
      { sentence: "병원은 지하철역 옆에 있어요.", translation: "The hospital is next to the subway station.", highlight: "병원" },
    ],
    collocations: [
      { phrase: "병원에 가다", translation: "to go to the hospital" },
      { phrase: "종합 병원", translation: "general hospital" },
    ],
    tags: ["place", "health"],
  },
  {
    id: "w_bus",
    word: "버스",
    romanization: "beoseu",
    ipa: "/pʌ̹.sɯ/",
    definitionEn: "bus",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "BEO-SEU → just say 'bus' with a Korean vowel. Same word.",
      syllables: ["버", "스"],
    },
    etymology: {
      origin: "bus (English)",
      language: "Loanword",
      rootWords: ["영어: bus"],
      originEn: "Direct transliteration of the English word 'bus'.",
    },
    examples: [
      { sentence: "버스를 타요.", translation: "I take the bus.", highlight: "버스" },
      { sentence: "버스가 늦게 와요.", translation: "The bus is coming late.", highlight: "버스" },
    ],
    collocations: [
      { phrase: "버스를 타다", translation: "to take the bus" },
      { phrase: "버스 정류장", translation: "bus stop" },
    ],
    tags: ["transport", "loanword"],
  },
  {
    id: "w_oneul",
    word: "오늘",
    romanization: "oneul",
    ipa: "/o̞.nɯɭ/",
    definitionEn: "today",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "O-NEUL → 'OH, KNEEL' — today, right now, you bow to begin.",
      syllables: ["오", "늘"],
    },
    etymology: {
      origin: "오늘",
      language: "Native",
      rootWords: ["Native Korean; the matching set is 어제 (yesterday) / 내일 (tomorrow)."],
      originEn: "Native Korean word. No Hanja root.",
    },
    examples: [
      { sentence: "오늘 날씨가 좋아요.", translation: "The weather is nice today.", highlight: "오늘" },
      { sentence: "오늘은 월요일이에요.", translation: "Today is Monday.", highlight: "오늘" },
    ],
    collocations: [
      { phrase: "오늘 아침", translation: "this morning" },
      { phrase: "오늘 밤", translation: "tonight" },
    ],
    antonyms: ["어제", "내일"],
    tags: ["time", "daily"],
  },
  {
    id: "w_eomeoni",
    word: "어머니",
    romanization: "eomeoni",
    ipa: "/ʌ̹.mʌ̹.ni/",
    definitionEn: "mother",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "EO-MEO-NI → 'UH, MA, KNEE' — tug at mother's knee.",
      syllables: ["어", "머", "니"],
    },
    etymology: {
      origin: "어머니",
      language: "Native",
      rootWords: ["Native Korean; casual form 엄마 is the toddler's first word."],
      originEn: "Pure Native Korean. The formal register is 어머님.",
    },
    examples: [
      { sentence: "저는 어머니를 사랑해요.", translation: "I love my mother.", highlight: "어머니" },
      { sentence: "어머니가 요리를 잘하세요.", translation: "My mother cooks well.", highlight: "어머니" },
    ],
    collocations: [
      { phrase: "어머니의 사랑", translation: "a mother's love" },
      { phrase: "어머님 (honorific)", translation: "mother (honorific)" },
    ],
    synonyms: ["엄마", "모친"],
    antonyms: ["아버지"],
    tags: ["family", "daily"],
  },
  {
    id: "w_gada",
    word: "가다",
    romanization: "gada",
    ipa: "/ka̠.da̠/",
    definitionEn: "to go",
    partOfSpeech: "VERB",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "GA-DA → 'GO, DA!' — the imperative to get going.",
      syllables: ["가", "다"],
    },
    etymology: {
      origin: "가다",
      language: "Native",
      rootWords: ["Native Korean; one of the most fundamental motion verbs."],
      originEn: "Native Korean verb. Irregular only in the honorific (가시다).",
    },
    examples: [
      { sentence: "학교에 가요.", translation: "I'm going to school.", highlight: "가" },
      { sentence: "어디에 가세요?", translation: "Where are you going?", highlight: "가" },
    ],
    collocations: [
      { phrase: "집에 가다", translation: "to go home" },
      { phrase: "놀러 가다", translation: "to go out to play / hang out" },
    ],
    antonyms: ["오다"],
    tags: ["verb", "motion"],
  },
  {
    id: "w_oda",
    word: "오다",
    romanization: "oda",
    ipa: "/o̞.da̠/",
    definitionEn: "to come",
    partOfSpeech: "VERB",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "O-DA → 'OH, DA!' — surprise arrival of someone.",
      syllables: ["오", "다"],
    },
    etymology: {
      origin: "오다",
      language: "Native",
      rootWords: ["Native Korean. Pairs with 가다 (to go) as motion opposites."],
      originEn: "Native Korean verb. Irregular in the connective form 와요.",
    },
    examples: [
      { sentence: "친구가 집에 와요.", translation: "A friend is coming to my house.", highlight: "와" },
      { sentence: "비가 와요.", translation: "It's raining. (literally 'rain is coming').", highlight: "와" },
    ],
    collocations: [
      { phrase: "집에 오다", translation: "to come home" },
      { phrase: "비가 오다", translation: "to rain" },
    ],
    antonyms: ["가다"],
    tags: ["verb", "motion"],
  },
  {
    id: "w_deopda",
    word: "덥다",
    romanization: "deopda",
    ipa: "/tʌ̹p̚.t͈a̠/",
    definitionEn: "to be hot (weather / a person feeling hot)",
    partOfSpeech: "ADJ",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "DEOP-DA → 'DUB DA fan on' — it's so hot.",
      syllables: ["덥", "다"],
    },
    etymology: {
      origin: "덥다",
      language: "Native",
      rootWords: ["Native Korean adjective (irregular ㅂ conjugation: 더워요)."],
      originEn:
        "Native Korean. Describes warm weather or a person's perceived heat, not physical hotness of objects (that's 뜨겁다).",
    },
    examples: [
      { sentence: "오늘 너무 더워요.", translation: "It's so hot today.", highlight: "더워" },
      { sentence: "여름에는 덥습니다.", translation: "It is hot in summer.", highlight: "덥" },
    ],
    collocations: [
      { phrase: "날씨가 덥다", translation: "the weather is hot" },
      { phrase: "더운 여름", translation: "a hot summer" },
    ],
    antonyms: ["춥다"],
    tags: ["weather", "adjective"],
  },
  {
    id: "w_ssada",
    word: "싸다",
    romanization: "ssada",
    ipa: "/s͈a̠.da̠/",
    definitionEn: "to be cheap; inexpensive",
    partOfSpeech: "ADJ",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "SSA-DA → 'SA-le DA price' — cheap.",
      syllables: ["싸", "다"],
    },
    etymology: {
      origin: "싸다",
      language: "Native",
      rootWords: ["Native Korean adjective."],
      originEn:
        "Native Korean. Note: a separate verb 싸다 means 'to wrap' — context and particle distinguish them.",
    },
    examples: [
      { sentence: "이 가방은 싸요.", translation: "This bag is cheap.", highlight: "싸" },
      { sentence: "시장이 백화점보다 더 싸요.", translation: "The market is cheaper than the department store.", highlight: "싸" },
    ],
    collocations: [
      { phrase: "값이 싸다", translation: "the price is cheap" },
      { phrase: "싼 가격", translation: "a low price" },
    ],
    antonyms: ["비싸다"],
    tags: ["shopping", "adjective"],
  },

  // ─── TOPIK I · Level 1 pack — wave 2 (school, time, motion, money) ───────
  {
    id: "w_haksaeng",
    word: "학생",
    romanization: "haksaeng",
    ipa: "/ha̠k̚.s͈ɛŋ/",
    definitionEn: "student",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "HAK-SAENG → 'HAWK SANG' in the classroom — a keen student.",
      syllables: ["학", "생"],
    },
    etymology: {
      origin: "學生",
      language: "Sino-Korean",
      rootWords: [
        { char: "學", meaning: "learn", sound: "학" },
        { char: "生", meaning: "person / being", sound: "생" },
      ],
      originEn: "學 (learn) + 生 (person) → 'a person who learns'.",
    },
    examples: [
      { sentence: "저는 학생이에요.", translation: "I am a student.", highlight: "학생" },
      { sentence: "교실에 학생이 많아요.", translation: "There are many students in the classroom.", highlight: "학생" },
    ],
    collocations: [
      { phrase: "대학생", translation: "university student" },
      { phrase: "유학생", translation: "international student" },
    ],
    antonyms: ["선생님"],
    tags: ["school", "people"],
  },
  {
    id: "w_seonsaengnim",
    word: "선생님",
    romanization: "seonsaengnim",
    ipa: "/sʰʌ̹n.sɛŋ.nim/",
    definitionEn: "teacher (polite)",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "SEON-SAENG-NIM → 'SUN SANG KNEE-M' — you bow to the teacher who shines first.",
      syllables: ["선", "생", "님"],
    },
    etymology: {
      origin: "先生님",
      language: "Sino-Korean",
      rootWords: [
        { char: "先", meaning: "first / before", sound: "선" },
        { char: "生", meaning: "born", sound: "생" },
      ],
      evolution: "先生 (Sino-Korean: 'one born before') + 님 (Native honorific suffix).",
      originEn: "先 (before) + 生 (born) → 'one born before (and therefore wiser)'. Add 님 for respect.",
    },
    morphology: { root: "선생", suffix: "님", note: "Sino-Korean compound + native honorific" },
    examples: [
      { sentence: "선생님, 안녕하세요.", translation: "Hello, teacher.", highlight: "선생님" },
      { sentence: "우리 선생님은 친절하세요.", translation: "Our teacher is kind.", highlight: "선생님" },
    ],
    collocations: [
      { phrase: "한국어 선생님", translation: "Korean-language teacher" },
      { phrase: "담임 선생님", translation: "homeroom teacher" },
    ],
    antonyms: ["학생"],
    tags: ["school", "people", "honorific"],
  },
  {
    id: "w_naeil",
    word: "내일",
    romanization: "naeil",
    ipa: "/nɛ.iɭ/",
    definitionEn: "tomorrow",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "NAE-IL → 'NAIL it tomorrow' — what's coming next.",
      syllables: ["내", "일"],
    },
    etymology: {
      origin: "來日",
      language: "Sino-Korean",
      rootWords: [
        { char: "來", meaning: "come", sound: "내" },
        { char: "日", meaning: "day", sound: "일" },
      ],
      originEn: "來 (coming) + 日 (day) → 'the day that is coming'.",
    },
    examples: [
      { sentence: "내일 만나요.", translation: "See you tomorrow.", highlight: "내일" },
      { sentence: "내일은 토요일이에요.", translation: "Tomorrow is Saturday.", highlight: "내일" },
    ],
    collocations: [
      { phrase: "내일 아침", translation: "tomorrow morning" },
      { phrase: "내일 저녁", translation: "tomorrow evening" },
    ],
    antonyms: ["어제"],
    tags: ["time", "daily"],
  },
  {
    id: "w_eoje",
    word: "어제",
    romanization: "eoje",
    ipa: "/ʌ̹.d͡ʑe̞/",
    definitionEn: "yesterday",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "EO-JE → 'UH, JAY' — yesterday, I saw my friend J.",
      syllables: ["어", "제"],
    },
    etymology: {
      origin: "어제",
      language: "Native",
      rootWords: ["Native Korean; pairs with 오늘 (today) and 내일 (tomorrow)."],
      originEn: "Native Korean word. No Hanja root.",
    },
    examples: [
      { sentence: "어제 영화를 봤어요.", translation: "I watched a movie yesterday.", highlight: "어제" },
      { sentence: "어제는 비가 왔어요.", translation: "It rained yesterday.", highlight: "어제" },
    ],
    collocations: [
      { phrase: "어제 저녁", translation: "yesterday evening" },
      { phrase: "바로 어제", translation: "just yesterday" },
    ],
    antonyms: ["내일"],
    tags: ["time", "daily"],
  },
  {
    id: "w_chupda",
    word: "춥다",
    romanization: "chupda",
    ipa: "/t͡ɕʰup̚.t͈a̠/",
    definitionEn: "to be cold (weather / a person feeling cold)",
    partOfSpeech: "ADJ",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "CHUP-DA → 'CHOP down' the firewood — it's cold outside.",
      syllables: ["춥", "다"],
    },
    etymology: {
      origin: "춥다",
      language: "Native",
      rootWords: ["Native Korean adjective (irregular ㅂ conjugation: 추워요)."],
      originEn: "Native Korean. Describes cold weather or a person feeling cold — not objects (차갑다).",
    },
    examples: [
      { sentence: "오늘 날씨가 추워요.", translation: "The weather is cold today.", highlight: "추워" },
      { sentence: "겨울에는 춥습니다.", translation: "It is cold in winter.", highlight: "춥" },
    ],
    collocations: [
      { phrase: "날씨가 춥다", translation: "the weather is cold" },
      { phrase: "추운 겨울", translation: "a cold winter" },
    ],
    antonyms: ["덥다"],
    tags: ["weather", "adjective"],
  },
  {
    id: "w_bissada",
    word: "비싸다",
    romanization: "bissada",
    ipa: "/pi.s͈a̠.da̠/",
    definitionEn: "to be expensive",
    partOfSpeech: "ADJ",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "BI-SSA-DA → 'BEE-SA-DA' — prefix 비 ('un-cheap') on 싸다 (cheap).",
      syllables: ["비", "싸", "다"],
    },
    etymology: {
      origin: "비싸다",
      language: "Native",
      rootWords: ["비 (Native intensifier prefix) + 싸다 (cheap)"],
      originEn: "Native Korean. The 비- prefix inverts the meaning of 싸다 — 'not cheap' → 'expensive'.",
    },
    morphology: { prefix: "비-", root: "싸다", note: "Negation prefix + adjective" },
    examples: [
      { sentence: "이 가방은 너무 비싸요.", translation: "This bag is too expensive.", highlight: "비싸" },
      { sentence: "서울의 집값은 비쌉니다.", translation: "House prices in Seoul are expensive.", highlight: "비싸" },
    ],
    collocations: [
      { phrase: "값이 비싸다", translation: "the price is high" },
      { phrase: "비싼 선물", translation: "an expensive gift" },
    ],
    antonyms: ["싸다"],
    tags: ["shopping", "adjective"],
  },
  {
    id: "w_ikda",
    word: "읽다",
    romanization: "ikda",
    ipa: "/ik̚.t͈a̠/",
    definitionEn: "to read",
    partOfSpeech: "VERB",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "ILK-DA → 'ILK, DA-ily' — read every day.",
      syllables: ["읽", "다"],
    },
    etymology: {
      origin: "읽다",
      language: "Native",
      rootWords: ["Native Korean verb; the ㄺ batchim only pronounces /k/ before a consonant."],
      originEn: "Native Korean verb. Spelling keeps both ㄹ and ㄱ; pronunciation drops to /ik̚/.",
    },
    examples: [
      { sentence: "저는 책을 읽어요.", translation: "I am reading a book.", highlight: "읽" },
      { sentence: "매일 신문을 읽습니다.", translation: "I read the newspaper every day.", highlight: "읽" },
    ],
    collocations: [
      { phrase: "책을 읽다", translation: "to read a book" },
      { phrase: "신문을 읽다", translation: "to read the newspaper" },
    ],
    antonyms: ["쓰다"],
    tags: ["verb", "school"],
  },
  {
    id: "w_sseuda",
    word: "쓰다",
    romanization: "sseuda",
    ipa: "/s͈ɯ.da̠/",
    definitionEn: "to write; to use",
    partOfSpeech: "VERB",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "SSEU-DA → 'SSSH, DRAW' — silently write with the pen.",
      syllables: ["쓰", "다"],
    },
    etymology: {
      origin: "쓰다",
      language: "Native",
      rootWords: ["Native Korean. Several homonyms share the form 쓰다: write, use, be bitter, wear (a hat)."],
      originEn:
        "Native Korean. Beginners meet 쓰다 = 'to write' first; context disambiguates the other meanings.",
    },
    examples: [
      { sentence: "편지를 써요.", translation: "I'm writing a letter.", highlight: "써" },
      { sentence: "이름을 여기에 쓰세요.", translation: "Please write your name here.", highlight: "쓰" },
    ],
    collocations: [
      { phrase: "편지를 쓰다", translation: "to write a letter" },
      { phrase: "이름을 쓰다", translation: "to write one's name" },
    ],
    antonyms: ["읽다"],
    tags: ["verb", "school"],
  },
  {
    id: "w_yeok",
    word: "역",
    romanization: "yeok",
    ipa: "/jʌ̹k̚/",
    definitionEn: "station (train / subway)",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "YEOK → 'YOKE' the trains together — the station connects them.",
      syllables: ["역"],
    },
    etymology: {
      origin: "驛",
      language: "Sino-Korean",
      rootWords: [{ char: "驛", meaning: "post station", sound: "역" }],
      originEn: "驛 originally meant a relay-horse post; re-used in modern Korean for train stations.",
    },
    examples: [
      { sentence: "서울역에서 만나요.", translation: "Let's meet at Seoul Station.", highlight: "역" },
      { sentence: "지하철역이 어디예요?", translation: "Where is the subway station?", highlight: "역" },
    ],
    collocations: [
      { phrase: "지하철역", translation: "subway station" },
      { phrase: "기차역", translation: "train station" },
    ],
    tags: ["place", "transport"],
  },
  {
    id: "w_eunhaeng",
    word: "은행",
    romanization: "eunhaeng",
    ipa: "/ɯn.ɦɛŋ/",
    definitionEn: "bank (financial institution)",
    partOfSpeech: "NOUN",
    level: 1,
    exam: "TOPIK_I",
    mnemonic: {
      englishHint: "EUN-HAENG → 'OON-HANG' your money here — silver (은) on a rack (행).",
      syllables: ["은", "행"],
    },
    etymology: {
      origin: "銀行",
      language: "Sino-Korean",
      rootWords: [
        { char: "銀", meaning: "silver", sound: "은" },
        { char: "行", meaning: "shop / firm", sound: "행" },
      ],
      originEn: "銀 (silver) + 行 (firm) → 'a firm that deals in silver (money)'.",
    },
    examples: [
      { sentence: "은행에 갔어요.", translation: "I went to the bank.", highlight: "은행" },
      { sentence: "은행은 9시에 문을 열어요.", translation: "The bank opens at 9.", highlight: "은행" },
    ],
    collocations: [
      { phrase: "은행 계좌", translation: "bank account" },
      { phrase: "은행에 가다", translation: "to go to the bank" },
    ],
    tags: ["place", "money"],
  },
];

export function findWord(id: string): Word | undefined {
  return SEED_WORDS.find((w) => w.id === id);
}

export function wordsByExam(exam: string) {
  return SEED_WORDS.filter((w) => w.exam === exam);
}
