"use client";

import Link from "next/link";
import { useState } from "react";

const SECTIONS = [
  {
    title: "Getting Started",
    items: [
      { q: "What is HangeulVision AI?", a: "An AI-powered Korean vocabulary platform. Every word gets a concept image, hanja breakdown, mnemonic, and spaced-repetition schedule — built for TOPIK, KIIP and EPS learners." },
      { q: "Is it free?", a: "Yes! The free tier includes 800 TOPIK I Level 1 words with flashcards, quizzes, and AI images. Upgrade to Basic or Premium for the full library." },
      { q: "How do I start learning?", a: "Sign up → take the Level Test (/study) to find your starting point → start reviewing flashcards on /review. The SM-2 algorithm schedules your reviews automatically." },
    ],
  },
  {
    title: "Exams & Content",
    items: [
      { q: "Which exams does it cover?", a: "TOPIK I (1-2급), TOPIK II Intermediate (3-4급), TOPIK II Advanced (5-6급), KIIP (사회통합프로그램), EPS-TOPIK (고용허가제), and thematic packs." },
      { q: "How many words are available?", a: "Currently 300+ seed words with AI images. The target is 12,000+ words across all exams, generated by our Claude + Stability AI pipeline." },
      { q: "What's the difference between Free, Basic, and Premium?", a: "Free: TOPIK I Level 1. Basic ($4.99/mo): TOPIK I full + TOPIK II Mid + KIIP. Premium ($7.99/mo): everything including EPS-TOPIK and theme packs." },
    ],
  },
  {
    title: "Learning Features",
    items: [
      { q: "How does spaced repetition work?", a: "We use SM-2 (same as Anki). Grade each card as 'Got it' or 'Don't know'. Cards you know appear less often; struggling words come back sooner." },
      { q: "What are the quiz modes?", a: "4 modes: Multiple Choice, Fill in Blank, Match Pairs, and 60-second Timed Challenge. All available on /quiz." },
      { q: "What is hanja decomposition?", a: "60%+ of Korean vocabulary comes from Sino-Korean roots (한자어). We break each compound into characters with meaning and reading — e.g. 감사 = 感(feel) + 謝(thank)." },
      { q: "Can I use it on my phone?", a: "Yes. HangeulVision is a PWA — install from your browser. Works offline on iOS and Android." },
    ],
  },
  {
    title: "Billing & Account",
    items: [
      { q: "How do I cancel my subscription?", a: "Go to /my (My Subscription) and click 'Cancel subscription'. You keep access until the billing period ends." },
      { q: "What's the refund policy?", a: "Subscriptions: 7-day full refund on first payment. One-time packs: non-refundable after access. See /refund-policy for details." },
      { q: "I forgot my password.", a: "Click 'Forgot password?' on the sign-in page. We'll email a reset link valid for 1 hour." },
      { q: "How do I delete my account?", a: "Go to /account → Danger Zone → Delete. This permanently removes all data (progress, bookmarks, sessions)." },
    ],
  },
];

export default function FaqPage() {
  const [openIdx, setOpenIdx] = useState<string | null>(null);

  return (
    <div className="mx-auto max-w-3xl py-6">
      <h1 className="text-3xl font-bold text-ink-900">Frequently Asked Questions</h1>
      <p className="mt-1 text-sm text-ink-500">Everything you need to know about HangeulVision AI.</p>

      <div className="mt-8 space-y-8">
        {SECTIONS.map((section) => (
          <div key={section.title}>
            <h2 className="mb-3 text-lg font-bold text-ink-900">{section.title}</h2>
            <div className="space-y-2">
              {section.items.map((item) => {
                const key = `${section.title}-${item.q}`;
                const isOpen = openIdx === key;
                return (
                  <div key={key} className="card overflow-hidden">
                    <button onClick={() => setOpenIdx(isOpen ? null : key)} className="flex w-full items-center justify-between p-4 text-left">
                      <span className="pr-4 text-sm font-semibold text-ink-900">{item.q}</span>
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={`shrink-0 text-ink-400 transition ${isOpen ? "rotate-180" : ""}`}><path d="M6 9l6 6 6-6" /></svg>
                    </button>
                    {isOpen && <div className="border-t border-gray-100 px-4 py-3 text-sm text-ink-700">{item.a}</div>}
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      <div className="mt-10 text-center">
        <p className="text-sm text-ink-500">Still need help?</p>
        <Link href="/contact" className="btn-primary mt-3 inline-block">Contact us</Link>
      </div>
    </div>
  );
}
