-- Add daily goals + streak tracking fields to User table
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bestStreak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyGoal" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyProgress" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastGoalReset" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastStudyDate" DATE;
