import PDFDocument from "pdfkit";

interface ReceiptData {
  transactionId: string;
  userName: string;
  userEmail: string;
  productName: string;
  amount: string;
  currency: string;
  date: Date;
  type: "subscription" | "one_time";
  plan?: string;
}

export function generateReceiptPDF(data: ReceiptData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(24).font("Helvetica-Bold").text("HangeulVision", 50, 50);
    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#666666")
      .text("AI Korean Vocabulary Platform", 50, 80);

    // Receipt title
    doc.moveDown(2);
    doc
      .fontSize(18)
      .font("Helvetica-Bold")
      .fillColor("#111111")
      .text("Payment Receipt", { align: "center" });

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#e5e7eb");
    doc.moveDown(1);

    // Details
    const labelX = 50;
    const valueX = 200;

    const addRow = (label: string, value: string) => {
      doc
        .fontSize(11)
        .font("Helvetica")
        .fillColor("#666666")
        .text(label, labelX, doc.y);
      doc.moveUp();
      doc.font("Helvetica-Bold").fillColor("#111111").text(value, valueX);
      doc.moveDown(0.5);
    };

    addRow("Transaction ID", data.transactionId);
    addRow(
      "Date",
      data.date.toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }),
    );
    addRow("Customer", data.userName);
    addRow("Email", data.userEmail);
    addRow("Product", data.productName);
    if (data.plan) addRow("Plan", data.plan);
    addRow(
      "Type",
      data.type === "subscription" ? "Subscription" : "One-time purchase",
    );

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#e5e7eb");
    doc.moveDown(1);

    // Amount
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .fillColor("#111111")
      .text("Total", labelX);
    doc.moveUp();
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .fillColor("#6366f1")
      .text(`${data.currency} ${data.amount}`, valueX);

    doc.moveDown(2);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#e5e7eb");
    doc.moveDown(2);

    // Footer
    doc
      .fontSize(9)
      .font("Helvetica")
      .fillColor("#999999")
      .text(
        "This receipt was automatically generated by HangeulVision.",
        { align: "center" },
      );
    doc.text("For questions, contact support@hangeulvision.app", {
      align: "center",
    });

    doc.end();
  });
}
